# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rainer\PycharmProjects\Akuvet2020\ui\dialogKunden.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogKunden(object):
    def setupUi(self, dialogKunden):
        dialogKunden.setObjectName("dialogKunden")
        dialogKunden.resize(667, 861)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogKunden)
        self.verticalLayout.setObjectName("verticalLayout")
        self.twkunden = QtWidgets.QTableView(dialogKunden)
        self.twkunden.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.twkunden.setAlternatingRowColors(False)
        self.twkunden.setGridStyle(QtCore.Qt.DashLine)
        self.twkunden.setSortingEnabled(True)
        self.twkunden.setObjectName("twkunden")
        self.verticalLayout.addWidget(self.twkunden)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogKunden)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(dialogKunden)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_searchfield = QtWidgets.QLineEdit(dialogKunden)
        self.le_searchfield.setObjectName("le_searchfield")
        self.horizontalLayout.addWidget(self.le_searchfield)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dialogKunden)
        self.buttonBox.accepted.connect(dialogKunden.accept)
        self.buttonBox.rejected.connect(dialogKunden.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogKunden)

    def retranslateUi(self, dialogKunden):
        _translate = QtCore.QCoreApplication.translate
        dialogKunden.setWindowTitle(_translate("dialogKunden", "Dialog"))
        self.label.setText(_translate("dialogKunden", "Suche:"))
