# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rainer\PycharmProjects\Akuvet2020\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(861, 159)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.in_user = QtWidgets.QLineEdit(self.splitter)
        self.in_user.setMinimumSize(QtCore.QSize(70, 30))
        self.in_user.setMaximumSize(QtCore.QSize(16777215, 30))
        self.in_user.setObjectName("in_user")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.in_password = QtWidgets.QLineEdit(self.splitter_2)
        self.in_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.in_password.setObjectName("in_password")
        self.verticalLayout.addWidget(self.splitter_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.submit_button = QtWidgets.QPushButton(self.splitter_4)
        self.submit_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.splitter_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.in_user)
        self.label_2.setBuddy(self.in_password)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Benutzer Name"))
        self.label_2.setText(_translate("Form", "Login"))
        self.submit_button.setText(_translate("Form", "Login"))
